codecov:
  branch: master

ignore:
  - "Kite-SDK/PSPrintSDK/AppDelegate*"
  - "Kite-SDK/PSPrintSDK/AssetDataSource*"
  - "Kite-SDK/PSPrintSDK/CI-ViewController*"
  - "Kite-SDK/PSPrintSDK/CustomAssetCollectionDataSource*"
  - "Kite-SDK/PSPrintSDK/NSData+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSString+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSURL+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLAnimation*"
  - "Kite-SDK/PSPrintSDK/OLCircularProgressView*"
  - "Kite-SDK/PSPrintSDK/OLFlipEnumerations*"
  - "Kite-SDK/PSPrintSDK/OLFlipTransition*"
  - "Kite-SDK/PSPrintSDK/OLFlipViewController*"
  - "Kite-SDK/PSPrintSDK/OLIndefiniteAnimatedView*"
  - "Kite-SDK/PSPrintSDK/OLKeyChainStore*"
  - "Kite-SDK/PSPrintSDK/OLMarkdownParser*"
  - "Kite-SDK/PSPrintSDK/OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLProgressHUD*"
  - "Kite-SDK/PSPrintSDK/OLRadialGradientLayer*"
  - "Kite-SDK/PSPrintSDK/OLTransition*"
  - "Kite-SDK/PSPrintSDK/OLTransitionEnumerations*"
  - "Kite-SDK/PSPrintSDK/RMImageCropper"
  - "Kite-SDK/PSPrintSDK/ViewController*"
  - "Kite-SDK/PSPrintSDK/main.m"
  - "Kite-SDK/Tests/Tests/*"
  - "Kite-SDK/Tests/Tests/CompleteJourneyTests.m"
  - "Kite-SDK/Tests/Tests/OLBaseRequest*"
  - "Kite-SDK/Tests/Tests/OLDocsObjcExampleCodeTests.m"
  - "Kite-SDK/Tests/Tests/OLKiteRequestTests.m"
  - "Kite-SDK/Tests/Tests/OLKiteTestHelper.m"
  - "Kite-SDK/Tests/Tests/OLMockPanGestureRecognizer.*"
  - "Kite-SDK/Tests/Tests/OLProductOrderTests.m"
  - "Kite-SDK/Tests/Tests/OLSDKModelTests.m"
  - "Kite-SDK/Tests/Tests/OLSwizzler.m"
  - "Kite-SDK/Tests/Tests/OLTestTapGestureRecognizer.*"
  - "Kite-SDK/Tests/Tests/UpsellTests.m"
  - "Kite-SDK/Tests/Tests/ViewControllerTests.m"
  - "Kite-SDK/Tests/Tests/XCTestCase*"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarNotification.*"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarStyle.*"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarView.*"